import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import MobileNavbar from "./_components/navigation/MobileNavbar";
import Topbar from "./_components/navigation/Topbar";
import Sidebar from "./_components/navigation/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function CompanyLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* MOBILE VIEW */}
        <div className="flex flex-col lg:hidden">
          <MobileNavbar />
          {children}
        </div>

        {/* DESKTOP VIEW */}
        <div className="hidden lg:grid grid-cols-[15dvw_85dvw] overflow-hidden">
          <Sidebar />
          <div className="grid grid-rows-[5dvh_95dvh] overflow-hidden">
            <Topbar />
            <div>
            {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
